name: Release
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Generate changelog
        run: npm install --no-package-lock --no-save emoji-regex && node changelog.js
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: changelog.md
          token: ${{ secrets.TOKEN }}
        env:
          GITHUB_REPOSITORY: my_gh_org/my_gh_repo
